#!/bin/sh

BACKUP_FOLDER=/opt/mysql/backup
NOW=$(date '+%d')

GZIP=$(which gzip)
MYSQLDUMP=$(which mysqldump)
MYSQL=$(which mysql)

### MySQL Server Login info ###
MDB=$MYSQL_DATABASE
MHOST=$MYSQL_CONTAINER_NAME
MPASS=$MYSQL_ROOT_PASSWORD
MUSER=root

[ ! -d "$BACKUP_FOLDER" ] && mkdir --parents $BACKUP_FOLDER

### MySQL DB Backup and GZIP ###
FILE=${BACKUP_FOLDER}/backup-${NOW}.sql.gz

$MYSQLDUMP -h $MHOST -u $MUSER -p${MPASS} --databases $MDB | $GZIP -9 > $FILE; && 

### MySQL DB Cleanup Table Pokemon (alles laenger als 7 Tage) ###
$MYSQL -h $MHOST -u $MUSER -p${MPASS} -D $MDB -e "DELETE FROM pokemon WHERE DATEDIFF(NOW(), last_modified) >= 7;" &&

### Delete Stops older 7 than days ###
$MYSQL -h $MHOST -u $MUSER -p${MPASS} -D $MDB -e "DELETE FROM pokestop WHERE last_updated < date_sub(now(), interval 7 day);" &&

### Delete Gyms older 7 than days ###
$MYSQL -h $MHOST -u $MUSER -p${MPASS} -D $MDB -e "DELETE FROM gym WHERE last_scanned < date_sub(now(), interval 7 day);" &&
$MYSQL -h $MHOST -u $MUSER -p${MPASS} -D $MDB -e "DELETE FROM gymdetails WHERE last_scanned < date_sub(now(), interval 7 day);" &&

### Delete Stops that became a Gym ###
$MYSQL -h $MHOST -u $MUSER -p${MPASS} -D $MDB -e "DELETE FROM pokestop where pokestop_id in (select gym_id from gym);"
