#!/bin/sh

BACKUP_FOLDER=/opt/mysql/backup
NOW=$(date '+%d')

GZIP=$(which gzip)
MYSQLDUMP=$(which mysqldump)
MYSQL=$(which mysql)

### MySQL Server Login info ###
MDB=$MYSQL_DATABASE
MHOST=$MYSQL_CONTAINER_NAME
MPASS=$MYSQL_ROOT_PASSWORD
MUSER=root

[ ! -d "$BACKUP_FOLDER" ] && mkdir --parents $BACKUP_FOLDER

### MySQL DB Cleanup Table Pokemon (alles laenger als 7 Tage) ###
# -> mysql -h DATENBANK_CONTAINER -u root -pPASSWORT_Root -D DATENBANK -e "DELETE FROM pokemon WHERE DATEDIFF(NOW(),last_modified) >= 7;"

FILE=${BACKUP_FOLDER}/backup-${NOW}.sql.gz
$MYSQLDUMP -h $MHOST -u $MUSER -p${MPASS} --databases $MDB | $GZIP -9 > $FILE; && 
$MYSQL -h $MHOST -u $MUSER -p${MPASS} -D $MDB -e "DELETE FROM pokemon WHERE DATEDIFF(NOW(),last_modified) >= 7;"
